### ISSUE TITLE
Error: This callback function has already been called by someon\ e else; it can only be called one time

### ISSUE THREAD

**Issue by webdeck** [sean9keenan/BigAssFansAPI#5]
Tried the new platform version, and got this error whenever the iOS Home app tried to identify one of my fans:

Sun, 18 Sep 2016 22:54:28 GMT Accessory [Family Room Fan] Identification request
[9/18/2016, 3:54:28 PM] [Haiku Fan] Family Room Fan Identify!!!
[9/18/2016, 3:54:28 PM] [Haiku Fan] Family Room Fan Identified fan (homekit setup)
/opt/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /opt/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at PlatformAccessory.<anonymous> (/opt/local/lib/node_modules/homebridge-bigAssFans/index.js:101:5)
    at emitTwo (events.js:92:20)
    at PlatformAccessory.emit (events.js:172:7)
    at PlatformAccessory.<anonymous> (/opt/local/lib/node_modules/homebridge/lib/platformAccessory.js:142:12)
    at emitTwo (events.js:87:13)
    at Accessory.emit (events.js:172:7)
    at Accessory._identificationRequest (/opt/local/lib/node_modules/homebridge\
/node_modules/hap-nodejs/lib/Accessory.js:109:10)
    at Accessory.<anonymous> (/opt/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:818:14)
    at emitThree (events.js:97:13)

**Comment by webdeck** [comment]
Sorry, wrong project.
